### ISSUE TITLE
delete repository or mark as deprecated

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/tilelive-gl#39]
We've decided to cease development on tilelive-gl -- it just makes more sense to use node-mapbox-gl-native directly in the use cases we are interested in.

We should indicate in the README that this library is deprecated and no longer maintained, or simply delete it outright.

**Comment by mikemorris** [comment]
No `dependents` listed on https://www.npmjs.com/package/tilelive-gl, I'd be inclined to just delete it.
